apiVersion: v1
kind: Service
metadata:
  name: "{{ appNamespace }}-api-service"
  namespace: "{{ appNamespace }}"
spec:
  selector:
    app: "{{ appNamespace }}-api"
  ports:
    - port: 80
      targetPort: 8000
