apiVersion: v1
kind: Secret
metadata:
  name: "{{ appNamespace }}-secrets"
  namespace: "{{ appNamespace }}"
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:<password>@{{ appNamespace }}-postgres-service:5432/marketpulse"
  RESEND_API_KEY: "<key>"
  JWT_SECRET: "k.jsdwu^776we67"
  POSTGRES_PASSWORD: "<password>"
